### ISSUE TITLE
Clang messages can not close 

### ISSUE THREAD

**Issue by Hungpro3112** [clangd/coc-clangd#317]
I use coc-clangd and i have this issue on [https://github.com/clangd/clangd/issues/833](url)
They said it related to coc-clangd.

Is this is bug or i miss config ?

Thanks for your help

**Comment by fannheyward** [comment]
Upgrade your coc.nvim to latest release, this has been fixed already.

**Comment by Hungpro3112** [comment]
> What's your `CocInfo`? Upgrade your coc.nvim to latest release, this has been fixed already.

Here my `CocInfo`

![image](https://user-images.githubusercontent.com/75968004/128445049-aff74295-9ab3-40b5-befc-b8035e81c887.png)

I coc.nvim is up to date but it doesn't fix

**Comment by fannheyward** [comment]
@Hungpro3112 https://github.com/neoclide/coc.nvim/issues/3171

**Comment by fannheyward** [comment]
@Hungpro3112 upgrade your coc to latest release and try again.

**Comment by Hungpro3112** [comment]
> @Hungpro3112 upgrade your coc to latest release and try again.

It works. Thank you
